# Generated by Django 6.0.6 on 2026-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_age', models.IntegerField(default=0)),
                ('donor_contact', models.IntegerField(default=0)),
                ('blood_group', models.IntegerField(default=0)),
            ],
        ),
    ]
