# Generated by Django 6.0.6 on 2026-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_donors',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='add_donors',
            name='donor_age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='add_donors',
            name='donor_contact',
            field=models.IntegerField(default=None),
        ),
    ]
