# Generated by Django 6.0.6 on 2026-06-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0002_alter_add_donors_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_donors',
            name='donor_contact',
            field=models.CharField(max_length=10),
        ),
    ]
