# Generated by Django 6.0.6 on 2026-06-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0003_alter_add_donors_donor_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(default=True)),
                ('patient_contact', models.CharField(max_length=10)),
                ('patient_bg', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_area', models.CharField(max_length=500)),
                ('blood_units', models.IntegerField(default=1)),
                ('last_date', models.DateField()),
            ],
        ),
    ]
