# Generated by Django 6.0.6 on 2026-06-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0004_blood_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('donated', 'Donated'), ('droped', 'Droped')], max_length=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodnet.blood_request')),
            ],
        ),
    ]
