# Generated by Django 6.0.6 on 2026-06-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0005_donation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_history',
            name='action',
            field=models.CharField(choices=[('donated', 'Donated'), ('dropped', 'Dropped')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donation_history',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodnet.blood_request'),
        ),
    ]
