# Generated by Django 6.0.6 on 2026-06-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0006_alter_donation_history_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_history',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation_history',
            name='paitent_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation_history',
            name='paitent_bg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation_history',
            name='paitent_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation_history',
            name='paitent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
