# Generated by Django 6.0.6 on 2026-06-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0007_donation_history_hospital_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation_history',
            old_name='paitent_age',
            new_name='patient_age',
        ),
        migrations.RenameField(
            model_name='donation_history',
            old_name='paitent_bg',
            new_name='patient_bg',
        ),
        migrations.RenameField(
            model_name='donation_history',
            old_name='paitent_contact',
            new_name='patient_contact',
        ),
        migrations.RenameField(
            model_name='donation_history',
            old_name='paitent_name',
            new_name='patient_name',
        ),
    ]
