# Generated by Django 6.0.6 on 2026-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0008_rename_paitent_age_donation_history_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_history',
            name='blood_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
