# Generated by Django 6.0.6 on 2026-06-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0010_donor_appointment_permanent_rejection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='add_donors',
            name='area_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blood_request',
            name='assigned_area_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blood_request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blood_request',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation_history',
            name='area_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='add_donors',
            name='donor_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add_donors',
            name='donor_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='blood_request',
            name='hospital_area',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blood_request',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blood_request',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blood_request',
            name='patient_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donation_history',
            name='patient_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation_history',
            name='patient_bg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation_history',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('area_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='add_donors',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodnet.area'),
        ),
        migrations.AddField(
            model_name='blood_request',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodnet.area'),
        ),
        migrations.CreateModel(
            name='TerminatedAreaManagerBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=150)),
                ('manager_username', models.CharField(max_length=150)),
                ('terminated_at', models.DateTimeField(auto_now_add=True)),
                ('donor_data', models.JSONField(default=list)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodnet.area')),
            ],
        ),
    ]
