# Generated by Django 6.0.6 on 2026-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodnet', '0011_add_donors_area_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDonorBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_age', models.IntegerField(default=0)),
                ('donor_contact', models.CharField(max_length=25)),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('last_donation', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
