# Generated by Django 6.0.6 on 2026-06-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'District_Manager'), (0, 'Admin'), (2, 'Area Manager')], default=0),
        ),
    ]
