# Generated by Django 6.0.6 on 2026-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_area_alter_user_contact_alter_user_id_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (2, 'Area Manager'), (1, 'District_Manager')], default=0),
        ),
    ]
