# Generated by Django 6.0.6 on 2026-06-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_contact_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'District_Manager'), (0, 'Admin'), (2, 'Area Manager')], default=0),
        ),
    ]
