# Generated by Django 6.0.6 on 2026-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (2, 'Area Manager'), (1, 'District_Manager')], default=0),
        ),
    ]
